### ISSUE TITLE
Build information missing

### ISSUE THREAD

**Issue by jdittrich** [Lakens/TOSTER#12]
**Story:** As a potential collaborator on the project, I would like to know how I can build the package (create package, load code for testing during development, generate documentation etc.)

**Comment by Lakens** [comment]
This package was built from Rstudio. 
I used the commands from the Build tab (Check, Build Source Package). 
I followed the excellent primer by Karl Broman: http://kbroman.org/pkg_primer/ 
Beyond this, I don't think you need build the package yourself. I will always maintain the package, build it, and upload it to CRAN. You can test functions without building the package - as long as functions work, they can be added to the package. If you want to create a complete function  including documentation, you can adjust one off the existing functions (e.g., https://github.com/Lakens/TOSTER/blob/master/R/TOSTtwo.R) and the documentation should be generated automatically when the package is built.
