### ISSUE TITLE
Implement robust test 

### ISSUE THREAD

**Issue by jdittrich** [Lakens/TOSTER#13]
**Story:** I want to apply the TOST on a sample that is not ideal for a t-test: Outliers, non-normal distribution or even ordinal data.

**Possible solution:** Instead of a t-Test, use 

* the  [Mann–Whitney U test](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test) (or also: "Wilcoxon Rank Sum Test")  on independent samples 
* the [Wilcoxon signed-rank test](https://en.wikipedia.org/wiki/Wilcoxon_signed-rank_test) on paired samples.

Both, Man-W-U and Wilcoxon-s-r tests are implemented in the R base package: http://stat.ethz.ch/R-manual/R-patched/library/stats/html/wilcox.test.html

**Comment by Lakens** [comment]
I agree this is a desirable test to add. I'm working on some new functions for proportions, and updating the power functions so they calculate power, given a sample size. But after that.

**Comment by SvenHeimbuch** [comment]
I would also like to see an implementation of non-parametric equivalence test and/or an option for Bootstrapping parameters.

**Comment by arcaldwell49** [comment]
See [documentation](https://aaroncaldwell.us/TOSTERpkg/articles/robustTOST.html)
