### ISSUE TITLE
P values reversed in output for TOST correlations 

### ISSUE THREAD

**Issue by dsquintana** [Lakens/TOSTER#27]
When using the `dataTOSTr` function, the lower p-value is associated with the bound that is closest to the confidence interval—this should be the other way around.

This is demonstrated in the attached screenshot, using the "Big 5" dataset from JASP, with the following script 

`dataTOSTr(data = data,
          pairs = list(
            list(
              i1="Extraversion",
              i2="Agreeableness")),
          low_eqbound_r = -0.15,
          high_eqbound_r = 0.15,
          desc = TRUE,
          plots = TRUE)`

<img width="1275" alt="screen shot 2018-05-05 at 15 50 12" src="https://user-images.githubusercontent.com/8218312/39665172-2b1ea8c0-5090-11e8-8e5e-f60b455a9724.png">

**Comment by Lakens** [comment]
Thanks for reporting this - we have fixed this error on the version that is on GitHub now, and we will soon be pushing it to CRAN. Thank you for reporting this issue - we are very grateful in your help to improve the accuracy of this package.
