### ISSUE TITLE
new version to the jamovi library

### ISSUE THREAD

**Issue by jonathon-love** [Lakens/TOSTER#28]
let me know if/when you need me to push an updated version to the jamovi library.

cheers

**Comment by Lakens** [comment]
Hi @jonathon-love - I've fixed the p-value switch bug in dataTOSTr - updated version to 0.3.3. It would be good if this is an updated version in the jamovi library to fix the bug that was reported, and get the test for proportions as a new feature in jamovi. Submitted 0.3.3 to CRAN today as well.

**Comment by jonathon-love** [comment]
will do

**Comment by jonathon-love** [comment]
in our jamovi library description, we have:

<img width="744" alt="screen shot 2018-05-08 at 19 24 20" src="https://user-images.githubusercontent.com/3240247/39749224-78421b84-52f5-11e8-94a3-4d3bacd9f714.png">

which links to here:

https://psyarxiv.com/97gpc/

is that link still the best link? did you want to embellish the description at all?

jonathon

**Comment by Lakens** [comment]
This is still the best link - if we decide to change it, I know where to in the future!
