### ISSUE TITLE
Minimal Effects Testing

### ISSUE THREAD

**Issue by StacyTShaw** [Lakens/TOSTER#30]
It would be great if there was a way to conduct a minimal effects test within the **TOSTtwo** function where you could set **high_eqbound_d = NA** or otherwise remove it to test for a minimal effect size between the two groups.

**Comment by Lakens** [comment]
If we incorporate this we should also include an option for non-inferiority tests. Right now, the solution is just to set a very high or low bound (e.g., low_eqbound = -999) for the test you want to ignore. This will test against an extreme value, give a p = 0.00000000000000000000000001, such that the other test value is always larger, and the important one for the final TOST decision. Incorporating this more systematically would require several changes in the output (suppressing half of the values) and new commands. I'm right now doubting whether this is worth it. The extreme value for the bound you are not interested in is a bit of a hack, but not too difficult to understand.
