### ISSUE TITLE
Clarity of the two Welch's tests in TOSTtwo function

### ISSUE THREAD

**Issue by StacyTShaw** [Lakens/TOSTER#31]
The two t-tests produced by the TOSTtwo function might benefit from some clarity as to what they are testing. The only distinction between them is that it is that the second is the "equivalency test", but with the focus of the package on equivalency testing, it's a bit ambigious as to what the first test is doing. 

Maybe the first test can be referred to as the "traditional Welch's t-test for group differences [Null test against difference of 0]" or something, and the second could be the Welch's t-test for equivalency. 

You might also consider reversing the order these are presented in as well, since most people will be interested in the equivalency test.

**Comment by Lakens** [comment]
The output has been reprogrammed and should now be clearer. This is not yet on CRAN but it is on GitHub.
