### ISSUE TITLE
missing values in the output

### ISSUE THREAD

**Issue by mdelacre** [Lakens/TOSTER#33]
![image](https://user-images.githubusercontent.com/28041451/43528055-60cf139e-95a8-11e8-997b-f72310032061.png)

Why the values of Z_L and Z_U  are missing from the output when performing an equivalence test for correlation? This makes it impossible to extract these values, what can be useful when performing monte carlo simulations :)

z_L <-(log((1 + r)/(1-r))/2-log((1 + low_eqbound_r)/(1 - low_eqbound_r))/2)/(1/sqrt(n - 3))
z_U <-(log((1 + r)/(1-r))/2-log((1 + high_eqbound_r)/(1 - high_eqbound_r))/2)/(1/sqrt(n - 3))

Best,

Marie

**Comment by Lakens** [comment]
This is fixed in the package version on GitHub (it is not yet on CRAN).
