### ISSUE TITLE
add more casual language interpretation of results

### ISSUE THREAD

**Issue by Lakens** [Lakens/TOSTER#44]
... we can conclude that the observed effect is statistically not different from zero and statistically equivalent to unsubstantial.

proposed by Anne Pier

**Comment by Lakens** [comment]
By Dorothy Bishop

I did wonder also about the TOSTER wording:
Based on the equivalence test and the null-hypothesis test combined, we can conclude that the observed effect is statistically different from zero and statistically equivalent to zero.
It does seem a bit like Schrödinger's cat. I wondered about rewording such as:
Based on the equivalence test and the null-hypothesis test combined, we can conclude that the observed effect is statistically different from zero but falls within the bounds that indicate the difference from zero is not meaningful.

**Comment by Glitchy-Tozier** [comment]
That new description you're proposing makes a lot of sense to me.
