### ISSUE TITLE
Equivalence bounds in visual and results set wrong

### ISSUE THREAD

**Issue by acircleda** [Lakens/TOSTER#49]
Whenever I set upper and lower bounds, the graph and results seem to indicate a much different equivalence bound than inputted. For example, the following code with an equivalence bound of .10 sets the bounds at near -.2 and near .08. Should they not be -.1 and .1? This effects both the results and the visual:

`TOSTtwo(m1=3.15, m2=3.08, sd1=.63, sd2=.76, n1=124, n2=395, low_eqbound_d=-.26, high_eqbound_d=.10, alpha = 0.05)`

![image](https://user-images.githubusercontent.com/51770624/72167223-c0bed980-3398-11ea-8a73-b6f8cc46bbfb.png)

Results read:

> Equivalence Test Result:
> The equivalence test was non-significant, t(245.09) = 0.00288, p = 0.501, given equivalence bounds of -0.181 and 0.0698 (on a raw scale) and an alpha of 0.05.

**Comment by Lakens** [comment]
Hi, the mean difference in the plot is on the RAW scale, not the standardized scale. This is done intentionally – we want people to think about what their standardized scores mean in raw differences. I think we should add (raw scale) on the label to clarify. I hope to work on the package somewhere this summer latest, and will add this issue to the to do list.

Daniel

**Comment by acircleda** [comment]
Thank you! I didn't realize it was converting it.
