### ISSUE TITLE
Request: Allow unbalanced samples for power analyses (e.g., `powerTOSTtwo`)

### ISSUE THREAD

**Issue by daaronr** [Lakens/TOSTER#59]
I'm looking to do some power calculations (or plots) of equivalence tests for comparing two samples of _different_ sizes. 
While `tsum_TOST` allows unbalanced samples, `powerTOSTtwo` does not (or at least I couldn't find it). 

Of course I should be able to do this with simulation, but it would be nice to use the `powerTOSTtwo` command involving analytical methods ("The exact calculations of power are based on Owen’s Q-function or by direct integration of the bivariate non-central t-distribution ...")

**Comment by arcaldwell49** [comment]
Hi, sorry I just now saw this comment!

I will look into this but you may want to check out the powerTOST package; it does much more than what I will implement in TOSTER.

https://cran.r-project.org/web/packages/PowerTOST/index.html

**Comment by daaronr** [comment]
Thank you
