### ISSUE TITLE
Link to educational material not locked behind a sign-up

### ISSUE THREAD

**Issue by Glitchy-Tozier** [Lakens/TOSTER#68]
In the readme, there is a reference to this page: https://www.coursera.org/teach/improving-statistical-questions

I would like to suggest uploading those videos to a platform where they are publicly available (whithout the need to sign up) and update the readme's link accordingly.

**Comment by Lakens** [comment]
Hi, the platform offers a superior learning experience compared to inline platforms as youtube, and it is free. There is no problem signing up with any email account. Furthermore, the information is already made available in many other locations (https://lakens.github.io/statistical_inferences/equivalencetest.html and https://www.youtube.com/watch?v=A0wrFrTltS4).
