### ISSUE TITLE
Documentation: for t_TOST add reference which data is used as mean difference center

### ISSUE THREAD

**Issue by typorian** [Lakens/TOSTER#73]
Hello there!
I have been using the t_TOST function of the TOSTER package. When looking into the documentation, it does not seem obvious to me which data should end up being the reference around which the mean difference to the other data is calculated.

In the documentation here https://aaroncaldwell.us/TOSTERpkg/reference/t_TOST.html there is a reference to passing the data as x and y, and the mean of the y data is what the center of the graphs will end up as. It would be good to indicate this or maybe even give a switch to define this.

**Comment by arcaldwell49** [comment]
Same as base R. Adding to documentation for next release.
