### ISSUE TITLE
Results from brunner_munzel() seem inverse of npar.t.test()

### ISSUE THREAD

**Issue by davidwcarter** [Lakens/TOSTER#82]
Why does the brunner_munzel() function report what seems like the inverse of the results reported by npar.t.test for the relative effect (p)? 

set.seed(123)
group1 <- rnorm(50, mean = 10, sd = 2)
group2 <- rnorm(50, mean = 11, sd = 3)
groups = data.frame(id=c(rep(1,50),rep(2,50)),g=c(group1,group2))

brunner_munzel(group1, group2,paired = FALSE,alternative = "two.sided")
brunner_munzel(group2, group1,paired = FALSE,alternative = "two.sided")

npt=npar.t.test(g~id,data=groups,alternative = "two.sided",method = "t.app")
summary(npt)

**Comment by davidwcarter** [comment]
Thanks for your clarification and for your great work on the TOST package. This is my first experience with the BM test and I was confused because the documentation for both functions appear to be defining the relative effect in the same way [p(X<Y) + .5*P(X=Y)], but yielding different results.  It would be helpful to have some clarification in the output as to which group the "X" and "Y" variables are assigned to, especially when the formula interface is used (e.g., brunner_munzel(g~id,data=groups,paired = FALSE,alternative = "two.sided")).

**Comment by arcaldwell49** [comment]
Looking back through the branches, I had it performing the tests that would be "[p(X<Y) + .5*P(X=Y)]" but flipped it for consistency with the other functions (i.e., Wilcoxon and t-tests).

**Comment by davidwcarter** [comment]
Good to hear that I am starting to understand this stuff. By the way, the describe_htest() function has been super useful in learning how these tests work. Thanks again for your help.
