### ISSUE TITLE
Incorrect formula used for dz variance

### ISSUE THREAD

**Issue by shaheedazaad** [Lakens/TOSTER#86]
I think the wrong formula might be implemented to compute variances for Cohen's _d<sub>z</sub>_

Right now, it's using formula 26 (Table 1) from Viechtbauer (2007):

```R
# vi[i] <- 1/ni[i] + (1 - (mi[i]-2)/(mi[i]*cmi[i]^2)) * yi[i]^2 # Viechtbauer, 2007d, equation 26; see [c]
d_sigma2 =  1/n + (1 - (d_df-2)/(d_df*J^2)) * cohend^2
d_sigma = sqrt(d_sigma2)
```

However, Table 1 provides variance estimators for $\delta_D$ and $\delta_2$, not $\delta_{D2}$ (i.e. _d<sub>z</sub>_ in Viechtbauer).

Table 2 provides variance estimates for $\delta_{D2}$. The unbiased estimate is given by formula 36.

**Comment by Lakens** [comment]
Hi, thanks so much for this comment. Could you add some information? Which formula are you discussing? Is this for the old TOSTpaired function, or the newer t_TOST function, or both? Thanks!

**Comment by arcaldwell49** [comment]
Hmm, the note in the code may be incorrect, but the function produces the "unbiased" estimate (vtype = "UB") from the SMCC of the metafor package. I'll need to check the Vietchbauer paper again to see what equation it actually is.

**Comment by arcaldwell49** [comment]
I believe you've misread the quoted article. Please re-read pages 42-44. In particular the equations immediately before and after equations 7 & 8.

**Comment by shaheedazaad** [comment]
> I believe you've misread the quoted article. Please re-read pages 42-44. In particular the text immediately before and after equations 7 & 8.

@arcaldwell49 I'm not sure which text specifically you're referring to, but the text I'm reading is the table titles. Equation 8 is the formula for _d_<sub>z</sub>, which Viechtbauer refers to as $\delta_{D2}$. The table on page 43 (Table 1) only gives variance estimators for $\delta_{2}$ and $\delta_{D}$ (formulae 2 and 7). Variance estimators for $\delta_{D2}$ are in Table 2 (page 45).

@Lakens I'm referring to the std error formula for d<sub>z</sub> described in the [SMD vignette](https://cran.r-project.org/web/packages/TOSTER/vignettes/SMD_calcs.html) - the last formula in the section titled _Cohen’s d(z): Change Scores_. I'm not sure which of those functions use this formula, but I could only find a reference to it in `d_est_pair()`

**Comment by arcaldwell49** [comment]
I believe you are mistaken. I'd check out metafor and the escalc function. We use the exact same unbiased estimator for the SMCC

**Comment by arcaldwell49** [comment]
So, to be clear, this is what $\delta_D$ refers to which is $d_z$ so Table 1 contains the correct standard error calculation

<img width="393" alt="Screenshot 2024-07-31 at 5 47 37 PM" src="https://github.com/user-attachments/assets/3fb0b7dc-9778-4259-b835-e4fa3cabaf67">


And this is what it says later about $\delta_{D2}$

<img width="571" alt="Screenshot 2024-07-31 at 5 51 14 PM" src="https://github.com/user-attachments/assets/d2c9c099-3147-4733-8aa2-6fa9c8570055">

I know it might be confusing, but the text is very clear *and* this is consistent with what Wolfgang has implemented in metafor.

**Comment by shaheedazaad** [comment]
> So, to be clear, this is what δD refers to which is dz so Table 1 contains the correct standard error calculation
> 
> <img alt="Screenshot 2024-07-31 at 5 47 37 PM" width="393" src="https://private-user-images.githubusercontent.com/24322628/354019334-3fb0b7dc-9778-4259-b835-e4fa3cabaf67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDMyOTcsIm5iZiI6MTcyMjUwMjk5NywicGF0aCI6Ii8yNDMyMjYyOC8zNTQwMTkzMzQtM2ZiMGI3ZGMtOTc3OC00MjU5LWI4MzUtZTRmYTNjYWJhZjY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA5MDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZDk2OWEzOTc2YTQ5OWI3YzIyNjIzZDdlYWM4Yjk5NTM2Y2JiNWVjODIxYTRlNjAzMTljMThhNjEwNzFmYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z_HiS8S17X1T3XCmaiUeA2HwlnIclKpB0Gz1kZ5I0rk">
> And this is what it says later about δD2
> 
> <img alt="Screenshot 2024-07-31 at 5 51 14 PM" width="571" src="https://private-user-images.githubusercontent.com/24322628/354019928-d2c9c099-3147-4733-8aa2-6fa9c8570055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDMyOTcsIm5iZiI6MTcyMjUwMjk5NywicGF0aCI6Ii8yNDMyMjYyOC8zNTQwMTk5MjgtZDJjOWMwOTktMzE0Ny00NzMzLThhYTItNmZhOWM4NTcwMDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA5MDMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ODM4ZWUxNDc4NWJhMDc1ZDIyYzcwNTUxOGM0NTA1OWUzZmY0YTZiYjFiYTE1NjcyYmM0Nzg1MDNiMDM1NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sa6Tx9grgW_M-Ff8bEDZP4k5bD5z_7Iw3D1YvElC468">
> I know it might be confusing, but the text is very clear _and_ this is consistent with what Wolfgang has implemented in metafor.

Ah, thanks for clarifying! I realise my mistake - I thought that the text above equation 8 was referring to the denominator for equation 8 and not 7!
